export type { Config } from "./src/config.ts";
export { config } from "./src/config.ts";

export type {
  AccountApiParameters,
  AccountInformation,
  BaseParameters,
  BaseResponse,
  GetBySearchIdParameters,
  Location,
  Locations,
  LocationsApiParameters,
} from "./src/types.d.ts";
export {
  getAccount,
  getHtml,
  getHtmlBySearchId,
  getJson,
  getJsonBySearchId,
  getLocations,
} from "./src/serpapi.ts";

export type {
  AppleAppStoreParameters,
  AppleProductParameters,
  AppleReviewsParameters,
  BaiduNewsParameters,
  BaiduParameters,
  BingImagesParameters,
  BingNewsParameters,
  BingParameters,
  DuckduckgoParameters,
  EbayParameters,
  EngineMap,
  GoogleAboutThisResultParameters,
  GoogleAutocompleteParameters,
  GoogleEventsParameters,
  GoogleFinanceMarketsParameters,
  GoogleImmersiveProductParameters,
  GoogleJobsListingParameters,
  GoogleJobsParameters,
  GoogleLensParameters,
  GoogleLocalServicesParameters,
  GoogleMapsParameters,
  GoogleMapsPhotosParameters,
  GoogleMapsReviewsParameters,
  GoogleParameters,
  GooglePlayParameters,
  GooglePlayProductParameters,
  GoogleProductParameters,
  GoogleRelatedQuestionsParameters,
  GoogleReverseImageParameters,
  GoogleScholarAuthorParameters,
  GoogleScholarCiteParameters,
  GoogleScholarParameters,
  GoogleScholarProfilesParameters,
  GoogleTrendsAutocompleteParameters,
  GoogleTrendsParameters,
  HomeDepotParameters,
  HomeDepotProductParameters,
  LinkedinParameters,
  LinkedinProfileParameters,
  NaverParameters,
  WalmartParameters,
  WalmartProductParameters,
  WalmartProductReviewsParameters,
  YahooImagesParameters,
  YahooParameters,
  YahooShoppingParameters,
  YahooVideosParameters,
  YandexImagesParameters,
  YandexParameters,
  YandexVideosParameters,
  YelpParameters,
  YelpReviewsParameters,
  YoutubeParameters,
} from "./src/engines/index.d.ts";
