import type { GoogleParameters } from "./google.d.ts";
import type { GoogleJobsParameters } from "./google_jobs.d.ts";
import type { GoogleJobsListingParameters } from "./google_jobs_listing.d.ts";
import type { GoogleReverseImageParameters } from "./google_reverse_image.d.ts";
import type { GoogleScholarProfilesParameters } from "./google_scholar_profiles.d.ts";
import type { GoogleScholarParameters } from "./google_scholar.d.ts";
import type { GoogleScholarCiteParameters } from "./google_scholar_cite.d.ts";
import type { GoogleScholarAuthorParameters } from "./google_scholar_author.d.ts";
import type { GoogleProductParameters } from "./google_product.d.ts";
import type { GoogleMapsParameters } from "./google_maps.d.ts";
import type { GoogleMapsPhotosParameters } from "./google_maps_photos.d.ts";
import type { GoogleMapsReviewsParameters } from "./google_maps_reviews.d.ts";
import type { GoogleEventsParameters } from "./google_events.d.ts";
import type { GoogleAutocompleteParameters } from "./google_autocomplete.d.ts";
import type { GoogleRelatedQuestionsParameters } from "./google_related_questions.d.ts";
import type { GoogleTrendsParameters } from "./google_trends.d.ts";
import type { GoogleTrendsAutocompleteParameters } from "./google_trends_autocomplete.d.ts";
import type { GoogleFinanceMarketsParameters } from "./google_finance_markets.d.ts";
import type { GoogleImmersiveProductParameters } from "./google_immersive_product.d.ts";
import type { BingParameters } from "./bing.d.ts";
import type { BingNewsParameters } from "./bing_news.d.ts";
import type { BingImagesParameters } from "./bing_images.d.ts";
import type { BaiduParameters } from "./baidu.d.ts";
import type { BaiduNewsParameters } from "./baidu_news.d.ts";
import type { YahooParameters } from "./yahoo.d.ts";
import type { YahooImagesParameters } from "./yahoo_images.d.ts";
import type { YahooVideosParameters } from "./yahoo_videos.d.ts";
import type { YahooShoppingParameters } from "./yahoo_shopping.d.ts";
import type { EbayParameters } from "./ebay.d.ts";
import type { YandexParameters } from "./yandex.d.ts";
import type { YandexImagesParameters } from "./yandex_images.d.ts";
import type { YandexVideosParameters } from "./yandex_videos.d.ts";
import type { YoutubeParameters } from "./youtube.d.ts";
import type { WalmartParameters } from "./walmart.d.ts";
import type { WalmartProductParameters } from "./walmart_product.d.ts";
import type { WalmartProductReviewsParameters } from "./walmart_product_reviews.d.ts";
import type { HomeDepotParameters } from "./home_depot.d.ts";
import type { HomeDepotProductParameters } from "./home_depot_product.d.ts";
import type { LinkedinParameters } from "./linkedin.d.ts";
import type { LinkedinProfileParameters } from "./linkedin_profile.d.ts";
import type { DuckduckgoParameters } from "./duckduckgo.d.ts";
import type { GooglePlayProductParameters } from "./google_play_product.d.ts";
import type { GooglePlayParameters } from "./google_play.d.ts";
import type { AppleAppStoreParameters } from "./apple_app_store.d.ts";
import type { AppleReviewsParameters } from "./apple_reviews.d.ts";
import type { AppleProductParameters } from "./apple_product.d.ts";
import type { NaverParameters } from "./naver.d.ts";
import type { GoogleLensParameters } from "./google_lens.d.ts";
import type { GoogleLocalServicesParameters } from "./google_local_services.d.ts";
import type { GoogleAboutThisResultParameters } from "./google_about_this_result.d.ts";
import type { YelpParameters } from "./yelp.d.ts";
import type { YelpReviewsParameters } from "./yelp_reviews.d.ts";

export type EngineMap = {
  google: { parameters: GoogleParameters };
  google_jobs: { parameters: GoogleJobsParameters };
  google_jobs_listing: { parameters: GoogleJobsListingParameters };
  google_reverse_image: { parameters: GoogleReverseImageParameters };
  google_scholar_profiles: { parameters: GoogleScholarProfilesParameters };
  google_scholar: { parameters: GoogleScholarParameters };
  google_scholar_cite: { parameters: GoogleScholarCiteParameters };
  google_scholar_author: { parameters: GoogleScholarAuthorParameters };
  google_product: { parameters: GoogleProductParameters };
  google_maps: { parameters: GoogleMapsParameters };
  google_maps_photos: { parameters: GoogleMapsPhotosParameters };
  google_maps_reviews: { parameters: GoogleMapsReviewsParameters };
  google_events: { parameters: GoogleEventsParameters };
  google_autocomplete: { parameters: GoogleAutocompleteParameters };
  google_related_questions: { parameters: GoogleRelatedQuestionsParameters };
  google_trends: { parameters: GoogleTrendsParameters };
  google_trends_autocomplete: {
    parameters: GoogleTrendsAutocompleteParameters;
  };
  google_finance_markets: { parameters: GoogleFinanceMarketsParameters };
  google_immersive_product: { parameters: GoogleImmersiveProductParameters };
  bing: { parameters: BingParameters };
  bing_news: { parameters: BingNewsParameters };
  bing_images: { parameters: BingImagesParameters };
  baidu: { parameters: BaiduParameters };
  baidu_news: { parameters: BaiduNewsParameters };
  yahoo: { parameters: YahooParameters };
  yahoo_images: { parameters: YahooImagesParameters };
  yahoo_videos: { parameters: YahooVideosParameters };
  yahoo_shopping: { parameters: YahooShoppingParameters };
  ebay: { parameters: EbayParameters };
  yandex: { parameters: YandexParameters };
  yandex_images: { parameters: YandexImagesParameters };
  yandex_videos: { parameters: YandexVideosParameters };
  youtube: { parameters: YoutubeParameters };
  walmart: { parameters: WalmartParameters };
  walmart_product: { parameters: WalmartProductParameters };
  walmart_product_reviews: { parameters: WalmartProductReviewsParameters };
  home_depot: { parameters: HomeDepotParameters };
  home_depot_product: { parameters: HomeDepotProductParameters };
  linkedin: { parameters: LinkedinParameters };
  linkedin_profile: { parameters: LinkedinProfileParameters };
  duckduckgo: { parameters: DuckduckgoParameters };
  google_play_product: { parameters: GooglePlayProductParameters };
  google_play: { parameters: GooglePlayParameters };
  apple_app_store: { parameters: AppleAppStoreParameters };
  apple_reviews: { parameters: AppleReviewsParameters };
  apple_product: { parameters: AppleProductParameters };
  naver: { parameters: NaverParameters };
  google_lens: { parameters: GoogleLensParameters };
  google_local_services: { parameters: GoogleLocalServicesParameters };
  google_about_this_result: { parameters: GoogleAboutThisResultParameters };
  yelp: { parameters: YelpParameters };
  yelp_reviews: { parameters: YelpReviewsParameters };
};
