import type { BaseParameters } from "../types.ts";

export type GoogleImmersiveProductParameters = BaseParameters & {
  /**
   * Page Token
   * Parameter defines the token needed to show more product info in Google immersive
   * popup. Token is generated by SerpApi using our [Google Immersive Product
   * API](https://serpapi.com/related-questions).
   */
  page_token: string;
};
