import type { BaseParameters } from "../types.d.ts";

export type GoogleRelatedQuestionsParameters = BaseParameters & {
  /**
   * Next Page Token
   * Parameter defines the token needed to show more Q&A pairs that Google generates
   * when a question gets clicked. Token is generated by SerpApi using our [Google
   * Related Questions API](https://serpapi.com/related-questions).
   */
  next_page_token: string;
};
